global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'ml_pipeline_metrics'
    static_configs:
      - targets: ['localhost:8000']  # Replace with your app's metrics endpoint.
