name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.11'
          cache: 'poetry'

      - name: Install Poetry
        run: poetry install

      - name: Run Tests
        run: poetry run invoke test
        env:
          PATH: ${{ env.PATH }}
